### ISSUE TITLE
Add unified binary

### ISSUE THREAD

**Issue by martinheidegger** [hyperswarm/cli#1]
When using `npx` you need to specify a package in order to access the swarm module:

```bash
npx -p @hyperswarm/cli hyperswarm-swarm
```

without the packages specification it will simply use the first binary specified in the package.json (it happens to be `discovery`):

https://github.com/hyperswarm/cli/blob/4d6814c7341155db6adbfba8405f8b07052e08ea/package.json#L6

I believe it would be good there was a simple, unified `hyperswarm` command with a `swarm` or `discovery` as first argument.

**Comment by mafintosh** [comment]
Ah, good idea. Fell free to PR it :)
